### ISSUE TITLE
problem with dplyr and rlang

### ISSUE THREAD

**Issue by rontomer** [r-lib/rlang#674]
Hi

Seems that something is not working with dplyr and rlang_0.3.0 since the last commit 
I get this error when trying use group_by,filter or any other function

```Error in filter_impl(.data, quo) : 
Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead.
```

Example

```
library(dplyr)
df <- data.frame(a=1:10)
df %>% filter(a>4)
```

Any idea what is the problem?

Session info
```
other attached packages:
 [1] bindrcpp_0.2        yaml_2.1.14         Ckmeans.1d.dp_4.2.1
 [4] tidyr_0.7.2         gridExtra_2.3       mailR_0.4.1
 [7] reshape2_1.4.3      reshape_0.8.7       scales_1.0.0
[10] ggplot2_3.0.0.9000  dplyr_0.7.4         RMySQL_0.10.13
[13] DBI_1.0.0           bigrquery_0.4.1     lubridate_1.7.4
[16] tidytext_0.1.4      xgboost_0.6-4       pROC_1.10.0
[19] slackr_1.4.2        devtools_1.13.3

loaded via a namespace (and not attached):
 [1] progress_1.2.0      purrr_0.2.4         rJava_0.9-6
 [4] lattice_0.20-35     colorspace_1.3-2    SnowballC_0.5.1
 [7] utf8_1.1.4          rlang_0.3.0         R.oo_1.21.0
[10] pillar_1.2.3        foreign_0.8-69      glue_1.2.0
[13] withr_2.1.2         R.utils_2.5.0       bindr_0.1
[16] plyr_1.8.4          stringr_1.3.1       munsell_0.5.0
[19] gtable_0.2.0        R.methodsS3_1.7.1   psych_1.7.8
[22] memoise_1.1.0       curl_3.0            parallel_3.4.2
[25] broom_0.4.2         tokenizers_0.1.4    Rcpp_0.12.19
[28] openssl_0.9.7       jsonlite_1.5        mnormt_1.5-5
[31] hms_0.4.2           digest_0.6.18       stringi_1.2.3
[34] cli_1.0.0           tools_3.4.2         magrittr_1.5
[37] lazyeval_0.2.1      tibble_1.4.2        janeaustenr_0.1.5
[40] crayon_1.3.4        pkgconfig_2.0.1     Matrix_1.2-11
[43] prettyunits_1.0.2   data.table_1.10.4-3 assertthat_0.2.0
[46] httr_1.3.1          R6_2.2.2            nlme_3.1-131
[49] compiler_3.4.2
```

**Comment by lionel-** [comment]
Can you call `traceback()` after triggering the error and paste the output here please?

**Comment by paupereda** [comment]
> Can you call `traceback()` after triggering the error and paste the output here please?

`16: stop(list(message = "Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.\nPlease use `as_data_pronoun()` instead.", 
        call = filter_impl(.data, quo), cppstack = NULL))
15: .Call(`_dplyr_filter_impl`, df, quo)
14: filter_impl(.data, quo)
13: filter.tbl_df(tbl_df(.data), ...)
12: filter(tbl_df(.data), ...)
11: as.data.frame(filter(tbl_df(.data), ...))
10: filter.data.frame(., a > 4)
9: filter(., a > 4)
8: function_list[[k]](value)
7: withVisible(function_list[[k]](value))
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(quote(`_fseq`(`_lhs`)), env, env)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: df %>% filter(a > 4)`

**Comment by lionel-** [comment]
oh I think you just need to update your dplyr to the latest version 0.7.7.

**Comment by rontomer** [comment]
Thanks @lionel- 
Upgrding to dplyr 0.7.7 did the tricj

**Comment by lionel-** [comment]
We can force dependencies to be at least a given version, but we currently have no mechanism for detecting out of date *reverse* dependencies :/

**Comment by gd047** [comment]
What is new in dplyr 0.7.7 ? 
Why there are no NEWS here? https://cran.r-project.org/web/packages/dplyr/news/news.html

**Comment by lionel-** [comment]
From https://github.com/tidyverse/dplyr/blob/v0.7.7/cran-comments.md, it looks like this was just a release to fix some CRAN check about NEWS.md.

**Comment by gd047** [comment]
Thank you. However I can't see how this minor update solved such a critical error (with rlang).

**Comment by lionel-** [comment]
Tomer was running dplyr 0.7.4, not 0.7.6.

**Comment by lionel-** [comment]
The switch from dictionary to data pronoun was an internal change and wouldn't appear in NEWS anyway.

**Comment by lionel-** [comment]
If many people are having this problem, this indicates we should have waited longer before removing these functions. Please add an emoji reaction to this message if you're reading this because youve encountered this error.

**Comment by philipodonnelllhh** [comment]
Would recommend waiting until the binaries are available on CRAN for dplyr > 0.7.4 before making a breaking change that requires 0.7.6

> install.packages("dplyr")
Installing package into ‘ ...
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
      binary source needs_compilation
dplyr  0.7.4  0.7.7              TRUE

Do you want to install from sources the package which needs compilation?
y/n:

**Comment by lionel-** [comment]
That's strange, there are dplyr binaries for Windows available: https://cran.r-project.org/bin/windows/contrib/3.5/dplyr_0.7.7.zip

Perhaps you're running an old R for which binaries are no longer compiled?

**Comment by lionel-** [comment]
Sorry about this. To install dplyr from source on Windows you need to:

* Install the latest Rtools (currently 3.5) from https://cran.r-project.org/bin/windows/Rtools/index.html. The tricky part is to ensure the Rtools directories are included in your `PATH`. The installer offers the option of editing the PATH.

* Install devtools from CRAN.

* Run `devtools::install_github("cran/dplyr")` to install the latest CRAN version of dplyr from source via the CRAN mirror on Github.

See https://www.biostat.wisc.edu/~kbroman/Rintro/Rwinpack.html for more detailed instructions. Let me know if you encounter issues.

**Comment by lionel-** [comment]
The easiest way is to update your R to the latest version, then you'll be able to install the latest dplyr binaries. Unfortunately binaries are not built for older versions.

**Comment by lionel-** [comment]
Now that I think of it, if you have the latest rlang installed on a version of R for which binaries are no longer built, that means that you installed it from source? So you have Rtools installed? Am I missing something?

**Comment by rilletlee** [comment]
Now, bugs occur when use ggpubr,
Warning message:
Computation failed in `stat_compare_means()`:
Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead. 
Should i use the old version rlang? Or, the problem is with its dependecies?

**Comment by rilletlee** [comment]
Wow! When I fixed the dplyr with the latest version, the warning massage disappeared.  
dplyr version 0.7.8
r version 3.5.0
all problem comes when choose to update all packages, so next time i'd be careful.

**Comment by lionel-** [comment]
If you update all your packages, you shouldn't run into this issue. It comes up when evaluating package A which depends on latest rlang, but not updating dplyr whose older versions are not compatible with latest rlang. If you update all packages (including dplyr), this shouldn't happen.

That's a forward compatibility problem, I'll be more careful about this next time.

**Comment by camilogavo** [comment]
Hi, I already update dplyr 0.7.8 but still having problems

R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS  10.14

What could be my issue?

**Comment by lionel-** [comment]
Could you post your `sessionInfo()` after a `library("dplyr")` please?

**Comment by lionel-** [comment]
(I assume you have restarted R after updating the packages)

**Comment by lionel-** [comment]
I don't understand how that's possible. I'm going to restore `as_dictionary()` in the next patch release of rlang, coming out next week.

@DanielAyllon @camilogavo Could you try installing that version and see if that fixes it please:

```r
remotes::install_github("r-lib/rlang@rc-0.3.1")
```

**Comment by DanielAyllon** [comment]
> 
> 
> I don't understand how that's possible. I'm going to restore `as_dictionary()` in the next patch release of rlang, coming out next week.
> 
> @DanielAyllon @camilogavo Could you try installing that version and see if that fixes it please:
> 
> ```r
> remotes::install_github("r-lib/rlang@rc-0.3.1")
> ```

Hey, I tried but couldn't install it. Got this error:

`Error: (converted from warning) running command '"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" CMD INSTALL -l "C:\Users\danay\Documents\R\win-library\3.3" "C:/Users/danay/AppData/Local/Temp/Rtmp8MyR3d/remotes28483f9a2a39/r-lib-rlang-fdadaba"' had status 1
In addition: Warning message:
In missing_devel_warning(pkgdir) :
  Package rlang has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
  Install Rtools (https://cran.r-project.org/bin/windows/Rtools/).Then use the pkgbuild package, or make sure that Rtools in the PATH.`

**Comment by lionel-** [comment]
Could you install Rtools please?

**Comment by DanielAyllon** [comment]
> 
> 
> Could you install Rtools please?

Rtools is already installed in my computer so I don't really know what the problem is...

**Comment by lionel-** [comment]
Perhaps you don't have it in your `PATH`. What does `Sys.getenv("PATH")` return?

**Comment by DanielAyllon** [comment]
> 
> 
> Perhaps you don't have it in your `PATH`. What does `Sys.getenv("PATH")` return?

I got inserted Rtools in my path and installed that rlang version from GitHub. Got the "filter" function from dplyr working but got also several warning messages:

Warning messages:
1: `as_dictionary()` is soft-deprecated as of rlang 0.3.0.
Please use `as_data_pronoun()` instead
This warning is displayed once per session. 
2: `new_overscope()` is soft-deprecated as of rlang 0.2.0.
Please use `new_data_mask()` instead
This warning is displayed once per session. 
3: The `parent` argument of `new_data_mask()` is deprecated.
The parent of the data mask is determined from either:

  * The `env` argument of `eval_tidy()`
  * Quosure environments when applicable
This warning is displayed once per session. 
4: `overscope_clean()` is soft-deprecated as of rlang 0.2.0.
This warning is displayed once per session.

**Comment by lionel-** [comment]
Sorry about that, you shouldn't get these messages. To help me figure out what's going on, can you:

1. Give the output of `rlang:::signal_soft_deprecated`
2. Give the output of the following, in a freshly restarted session:

```r
rlang::with_options(
  error = rlang::entrace,
  rlang:::with_lifecycle_errors(
    <<insert here the expression that gives the warnings>>
  )
)


rlang::last_error()
rlang::last_trace()
```

Also can you make a reprex with the reprex package please.

**Comment by DanielAyllon** [comment]
> 
> 
> Sorry about that, you shouldn't get these messages. To help me figure out what's going on, can you:
> 
>     1. Give the output of `rlang:::signal_soft_deprecated`
> 
>     2. Give the output of the following, in a freshly restarted session:
> 
> 
> ```r
> rlang::with_options(
>   error = rlang::entrace,
>   rlang:::with_lifecycle_errors(
>     <<insert here the expression that gives the warnings>>
>   )
> )
> 
> 
> rlang::last_error()
> rlang::last_trace()
> ```
> 
> Also can you make a reprex with the reprex package please.

Sure. 
Regarding (1):
```function (msg, id = msg, env = caller_env(2)) 
{
    stopifnot(rlang::is_string(msg), rlang::is_string(id), rlang::is_environment(env))
    if (rlang::is_true(rlang::peek_option("lifecycle_disable_warnings"))) {
        return(invisible(NULL))
    }
    env_inherits_global <- function(env) {
        if (rlang::is_reference(env, emptyenv())) {
            return(FALSE)
        }
        rlang::is_reference(topenv(env), rlang::global_env())
    }
    if (rlang::is_true(rlang::peek_option("lifecycle_verbose_soft_deprecation")) || 
        env_inherits_global(env)) {
        warn_deprecated(msg, id)
        return(invisible(NULL))
    }
    tested_package <- Sys.getenv("TESTTHAT_PKG")
    if (nzchar(tested_package) && identical(Sys.getenv("NOT_CRAN"), 
        "true") && rlang::env_name(topenv(env)) == rlang::env_name(ns_env(tested_package))) {
        warn_deprecated(msg, id)
        return(invisible(NULL))
    }
    rlang::signal(msg, "lifecycle_soft_deprecated")
}
<bytecode: 0x00000000153fed58>
<environment: namespace:rlang>```


Regarding (2):

```Error in filter_impl(.data, quo) : 
  Evaluation error: `as_dictionary()` is soft-deprecated as of rlang 0.3.0.
Please use `as_data_pronoun()` instead.
Call `rlang::last_error()` to see a backtrace
> rlang::last_error()
<error>
message: Evaluation error: `as_dictionary()` is soft-deprecated as of rlang 0.3.0.
Please use `as_data_pronoun()` instead.
class:   `rlang_error`
backtrace:
 1. rlang::with_options(...)
 3. global::plotgraphsAll(...)
 5. dplyr:::filter.data.frame(...)
 8. dplyr:::filter.tbl_df(tbl_df(.data), ...)
 9. dplyr:::filter_impl(.data, quo)
<error: parent>
message: Evaluation error: `as_dictionary()` is soft-deprecated as of rlang 0.3.0.
Please use `as_data_pronoun()` instead.
class:   `Rcpp::eval_error`
> rlang::last_trace()
    x
 1. +-rlang::with_options(...)
 2. +-rlang:::with_lifecycle_errors(...)
 3. \-global::plotgraphsAll(...)
 4.   +-dplyr::filter(mydata, SlotUpper == filter[1] & HookMort == HM)
 5.   \-dplyr:::filter.data.frame(...)
 6.     +-base::as.data.frame(filter(tbl_df(.data), ...))
 7.     +-dplyr::filter(tbl_df(.data), ...)
 8.     \-dplyr:::filter.tbl_df(tbl_df(.data), ...)
 9.       \-dplyr:::filter_impl(.data, quo)```

**Comment by lionel-** [comment]
Thank you. Could you make a reprex using the reprex package please?

Also could you provide the source of the function(s) you're using? You can send it by mail if you prefer not to reveal it here.

**Comment by lionel-** [comment]
@DanielAyllon There are two mysteries here.

First, you seem to have dplyr 0.7.8 installed, but it calls `as_dictionary()`. That's just not possible. My guess is that you tried to update dplyr, but the DLL failed to be updated. Could you reinstall dplyr and see if that fixes it please.

The second mystery is why you're getting lifecycle warnings. That shouldn't happen either. This is why I would like to see a reprex created with the reprex package, because that will make sure your code is run in a pristine session free of interferences.

**Comment by lionel-** [comment]
Here is an example of DLL failing to update:

```
Warning in file.copy(files, dest, overwrite = TRUE) :
  problem copying .\tibble.dll to C:\Users\Lionel\Documents\R\win-library\3.5\tibble\libs\x64\tibble.dll: Permission denied
```

This can be buried in the installation output if you've been compiling by source. Note that unfortunately the installation does _not_ fail. And if the external API has not changed, you won't get a crash when calling into the outdated DLL, so that installation problem might go completely unnoticed, causing strange behaviours as we are witnessing here.

This is a known issue of installing R packages on Windows because DLLs of packages loaded in R cannot be updated, on that platform. However in the example (created in a virtual machine, most R developers do not use Windows) above I have a permission issue. This could happen on Unixes as well, though I'm not sure what are the circumstances causing such issues...

Now, those deprecation warnings shouldn't happen either way because it's all R code and no DLL is involved :(

**Comment by philipodonnelllhh** [comment]
Hi Gents, it has been a while since I was dealing with this issue but I have seen a lot of activity so wanted to say that I traced it to version conflicts between the CRAN and the github versions of ggplot, rlang, dplyr and tibble. One of them had a dependency on 0.3.0 and another used the `as_dictionary` so would fail. I was trapped in a full day of dependency hell trying to resolve it until I uninstalled and started over being very careful about which versions I was installing and doing it from github @ versions where possible. 

Here is my current (working) session:

> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     crayon_1.3.4     dplyr_0.7.4      assertthat_0.2.0 grid_3.3.0       plyr_1.8.4       R6_2.3.0         gtable_0.2.0    
 [9] magrittr_1.5     scales_0.5.0     ggplot2_3.1.0    pillar_1.3.0     rlang_0.2.2      lazyeval_0.2.1   rstudioapi_0.8   bindrcpp_0.2.2  
[17] tools_3.3.0      glue_1.2.0       munsell_0.5.0    yaml_2.1.18      pkgconfig_2.0.2  colorspace_1.3-2 bindr_0.1.1      tibble_1.4.2    


Sorry I can't provide more detail but it was some time ago.

**Comment by lionel-** [comment]
@philipodonnelllhh You should update dplyr to the latest CRAN version to fix the issue. Since you're on Windows, be careful about dll-updating problems. Always install in a fresh session, and make sure dplyr is not loaded via your RProfile (sessionInfo should be empty before installing).

I would also update R to 3.5. You're no longer getting CRAN binaries with the old R 3.3, which makes updates painful.

**Comment by lionel-** [comment]
rlang 0.3.1 is on CRAN. This release cancels the defunction of `as_dictionary()`, and is now compatible with old dplyr versions again.

**Comment by lionel-** [comment]
I just learned about this very useful command to check whether your packages have been installed properly!

```r
tools::checkMD5sums("dplyr")
tools::checkMD5sums("rlang")
```

It works only on Windows, on macOS and Linux you'll get `NA`.

@DanielAyllon I would be interested in the output of these commands on your system, if you have time.

**Comment by kirannarta** [comment]
Hi.. I am facing issues related to dplyr and rlang while trying to run Rscript. 

**Initially I had this error:**
`Error: package or namespace load failed for ‘dplyr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.2.1 is already loaded, but >= 0.3.0 is required`. 

**I updated rlang to 0.3.0.1. **Now I am have the following error:****

`Attaching package: ‘dplyr’

The following objects are masked from ‘package:plyr’:

    arrange, count, desc, failwith, id, mutate, rename, summarise,
    summarize

The following object is masked from ‘package:reshape’:

    rename

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: plyr::split_indices(scale_id, n)
 2: scale_apply(layer_data, x_vars, "train", SCALE_X, x_scales)
 3: f(...)
 4: self$facet$train_scales(self$panel_scales_x, self$panel_scales_y,     layout, data, self$facet_params)
 5: f(..., self = self)
 6: layout$train_position(data, scale_x(), scale_y())
 7: ggplot_build.ggplot(x)
 8: ggplot_build(x)
 9: plot.ggplot(dotplot)
10: plot(dotplot)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault: 11`


**My sessionInfo is as follows:**
`> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin14.5.0 (64-bit)
Running under: macOS  10.14

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       crayon_1.3.4     dplyr_0.7.8      assertthat_0.2.0
 [5] grid_3.5.1       plyr_1.8.4       R6_2.2.2         gtable_0.2.0    
 [9] magrittr_1.5     scales_1.0.0     ggplot2_3.1.0    pillar_1.3.0    
[13] rlang_0.3.1      lazyeval_0.2.1   bindrcpp_0.2.2   glue_1.3.0      
[17] purrr_0.2.5      munsell_0.5.0    compiler_3.5.1   pkgconfig_2.0.1 
[21] colorspace_1.3-2 tidyselect_0.2.4 bindr_0.1.1      tibble_1.4.2    `

Any suggestion is appreciated!

**Comment by lionel-** [comment]
You likely had an installation error at some point. Please reinstall rlang (current version is 0.3.1) and especially dplyr.
